### ISSUE TITLE
Android version?

### ISSUE THREAD

**Issue by yeedatoy** [IamAzmathullaShaikh/OnePlus_CPH2467_Holi#1]
Thank you for this! The previous upload I didn't see the installer file so against my better judgement I used the previous one, and hoped it would boot into ofox and then I could use the updated image. I knew the risk, and got stuck at the ofox screen. I see the update, and I have the Nord n30 which is the same device. I am curious though about the Android version this is for. 13 or 14 or have you tried both? Thanks again. There's a lot of us waiting for this and we appreciate your work. If you could just clarify a few minor things like Android version that would be great

**Comment by IamAzmathullaShaikh** [comment]
Thanks to you for giving a hint to give it a try on A13 since i havent tried yet but now i will okay so coming to the point Its still In Testing State on A14 FBE Issue Is Not Resolved ive been trying all the possible ways to fix it. Now I shall release Next Build Which doesnt Cause Stuck at ORFOX Logo since the current build does stuck if not wiped data before getting into recovery. If You Want a Working OFOX Without FBE Support Kindly Give a Try From the Below Build Im Attaching [https://drive.google.com/file/d/1Us89xEEDXkdcMuI7ATAe7ZOG1GaulmX7/view?usp=sharing](url)

*Please follow Steps*
You Need To Have MicroSD In Mobile SInce Internal Doesnt Mount Because Of FBE Decrypt Issue then place Stock boot Of Your current OOS Rom and OrangeFox.img provided in link  in MicroSD
1.Flash OrangeFox to Boot_[ActiveSlot] in fastboot
2.Flash VBMETA Disable and VBmeta_system Disable in Fastboot
3Reboot To recovery
3.Flash Stock boot.img as boot in Orangefox Recovery later choose Orangefox.img and install as Recovery Ramdisk [It is Pre Magisk Patched]
 Voila Now You Have working ORFX with FBE Issue and some minor issues which im trying to fix.
But Your device wont Bootloop or DATA is Not Lost If You Follow Exactly.

**Comment by IamAzmathullaShaikh** [comment]
I have Upated The RElease Now You can Directly Download No FBE Release From Releases Section and Do Follow Steps Obsolute :0
